version: "3.10"

services:
  bengali-rag:
    build: .
    container_name: bengali-rag
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped